#!/usr/bin/env python

import sys
import git
import os
import requests


def postMessage():
  url = ""
  data = {'message': str(sys.argv[2])}
  headers = {'Content-type': 'application/json'}
  r = requests.post(url, data=json.dumps(data), headers=headers)
  # r.json
  return




def continue_commit_prompt():
  print "Your commit message is good. Do you want to continue your commit? [Y/n]"
  valid = {"": True, "yes": True, "y": True, "no": False, "n": False}
  choice = raw_input().lower()
  print valid[choice]
  return valid;


def git_commit():
  try:
    print repo.git.commit(m=str(sys.argv[2]))
  except git.exc.GitCommandError:
    print repo.git.status()
  return


repo = git.Repo(os.getcwd())
print "Number of arguements: ", len(sys.argv), 'arguements.'
print 'arguement list: ', str(sys.argv[2])

strHead = "?message="
print strHead+str(sys.argv[2])
continue_commit_prompt()
git_commit()
