#!/usr/bin/env python

import sys
import git
import os
import requests

repo = git.Repo(os.getcwd())
reader = repo.config_reader()
field = reader.get_value("user","email")
print field

repo.git.commit('-a', '', author=field)
